defaultPortal: Hubz
portals:
  - name: Hubz
    portalId: 21007727
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNzT7cjULxIJAA0AAAAA4A0DGO-aggoguJz_DCju6QwyFBkxnrTAVSM-XbvZu3jbRu3qVEB-OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTr4yQdpEuMM-tR3ye9VcfIU_pMN0oDbmExUgBaAA
        expiresAt: '2021-11-22T19:24:33.123Z'
    personalAccessKey: >-
      CiQ0NzdmN2RlOS1jMDMyLTRkNWYtOTVmNi0xZTIxY2EwYTYxYzQQ75qCChi4nP8MKhkABeaRgjbawefThK98yPaZF_tByunFBuYzSgNuYTE
